'use client';

import { useEffect, useRef, useState } from 'react';
import { Crown, GripVertical, Send, Share2, Sparkles, UsersRound, Volume2, X } from 'lucide-react';
import { friendQuestions, rankingCategories } from '@/lib/game';
import type { ClientEvent, GameMode, Player, QuestionSource, RoomState, Settings } from '@/shared/room-types';

const avatars = ['😎', '🐸', '🦊', '👽', '🐙', '🐧', '🦄', '🧃'];
const apiOrigin = (import.meta.env.VITE_LOBBY_API_ORIGIN || '').replace(/\/$/, '');
type Screen = 'home' | 'profile' | 'code' | 'lobby' | 'questions' | 'ranking' | 'waiting' | 'reveal';
type Session = { code: string; playerId: string; token: string };
const defaultSettings: Settings = { questionCount: 3, rounds: 2, mode: 'friends', questionSource: 'preset' };

function insert<T>(items: T[], from: number, to: number) { const next = [...items]; next.splice(to, 0, next.splice(from, 1)[0]); return next; }
function api(path: string, init?: RequestInit) { if (!apiOrigin) throw new Error('Der Multiplayer-Server ist noch nicht eingerichtet.'); return fetch(`${apiOrigin}${path}`, { headers: { 'Content-Type': 'application/json' }, ...init }); }

export default function Home() {
  const [screen, setScreen] = useState<Screen>('home'); const [name, setName] = useState(''); const [avatar, setAvatar] = useState('😎'); const [code, setCode] = useState(''); const [joinCode, setJoinCode] = useState(''); const [session, setSession] = useState<Session | null>(null); const [room, setRoom] = useState<RoomState | null>(null); const [error, setError] = useState(''); const [questions, setQuestions] = useState(['', '', '']); const [order, setOrder] = useState<string[]>([]); const [dragged, setDragged] = useState<string | null>(null); const socket = useRef<WebSocket | null>(null);
  const player = room?.players.find((entry) => entry.id === session?.playerId); const isHost = room?.hostId === session?.playerId;
  const send = (event: ClientEvent) => socket.current?.readyState === WebSocket.OPEN && socket.current.send(JSON.stringify(event));
  const connect = (next: Session) => { const wsOrigin = apiOrigin.replace(/^http/, 'ws'); const ws = new WebSocket(`${wsOrigin}/ws?code=${next.code}&playerId=${next.playerId}&token=${next.token}`); socket.current = ws; ws.onmessage = ({ data }) => { const event = JSON.parse(data); if (event.type === 'room_state') { setRoom(event.room); setOrder((current) => current.length === event.room.players.length ? current : event.room.players.map((p: Player) => p.id)); if (event.room.phase === 'question_draft') setScreen('questions'); if (event.room.phase === 'ranking') setScreen('ranking'); if (event.room.phase === 'reveal') setScreen('reveal'); } else if (event.type === 'error') setError(event.message); }; ws.onclose = () => setTimeout(() => session && connect(session), 2000); };
  useEffect(() => { const saved = localStorage.getItem('friends-rank-session'); if (!saved || !apiOrigin) return; const next = JSON.parse(saved); setSession(next); setCode(next.code); setScreen('lobby'); connect(next); return () => socket.current?.close(); }, []);
  const saveSession = (next: Session) => { localStorage.setItem('friends-rank-session', JSON.stringify(next)); setSession(next); setCode(next.code); connect(next); };
  const createRoom = async () => { try { const response = await api('/api/rooms', { method: 'POST', body: JSON.stringify({ name, avatar }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); saveSession(data); setScreen('lobby'); } catch (err) { setError(err instanceof Error ? err.message : 'Verbindung fehlgeschlagen.'); } };
  const joinRoom = async () => { try { const response = await api(`/api/rooms/${joinCode}/join`, { method: 'POST', body: JSON.stringify({ name, avatar }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); saveSession(data); setScreen('lobby'); } catch (err) { setError(err instanceof Error ? err.message : 'Beitritt fehlgeschlagen.'); } };
  const updateSettings = (patch: Partial<Settings>) => room && send({ type: 'settings_updated', settings: { ...room.settings, ...patch } });
  const start = () => send({ type: 'start_game' });
  const submitRanking = () => { send({ type: 'ranking_submitted', order }); setScreen('waiting'); };
  const question = room?.settings.mode === 'guess' ? rankingCategories[0].title : friendQuestions[0].text;

  return <main className={`game-shell screen-${screen}`}><div className="orb orb-one" /><div className="orb orb-two" /><header className="topbar"><button className="brand" onClick={() => setScreen('home')}><span className="brand-mark"><Crown size={20} /></span><span>FRIENDS<br />RANK</span></button>{room && <span className="room-code">RAUM <b>{room.code}</b></span>}<button className="icon-button" aria-label="Sound"><Volume2 size={20} /></button></header>{error && <div className="error-toast"><span>{error}</span><button onClick={() => setError('')}><X size={18} /></button></div>}
    {screen === 'home' && <section className="home-screen screen-enter"><div className="hero-copy"><p className="kicker"><Sparkles size={16} /> DAS PARTY-GAME FÜR DEINE CREW</p><h1>WAS DENKEN<br />DEINE FREUNDE<br /><span>WIRKLICH?</span></h1><p className="lede">Rankt euch gegenseitig. Diskutiert die Ergebnisse. Bereut nichts.</p><div className="hero-actions"><button className="button button-primary" onClick={() => { setJoinCode(''); setScreen('profile'); }}>SPIEL ERSTELLEN <span>→</span></button><button className="button button-secondary" onClick={() => setScreen('code')}>LOBBY BEITRETEN</button></div></div><div className="hero-stack" aria-hidden="true"><article className="floating-card card-ali"><span>🐸</span><strong>ALI</strong><small>Most chaotic</small></article><article className="floating-card card-mika"><span>🦊</span><strong>MIKA</strong><small>Would survive</small></article><article className="floating-card card-you"><span>😎</span><strong>DU?</strong><small>Find out</small></article></div></section>}
    {screen === 'code' && <section className="panel setup-screen screen-enter"><p className="eyebrow">PRIVATE LOBBY</p><h2>CODE EINGEBEN</h2><p>Gib den fünfstelligen Code der Person ein, die das Spiel erstellt hat.</p><input className="name-input code-input" value={joinCode} onChange={(e) => setJoinCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 5))} placeholder="F7K2Q" /><button className="button button-primary full" disabled={joinCode.length !== 5} onClick={() => setScreen('profile')}>WEITER <span>→</span></button></section>}
    {screen === 'profile' && <section className="panel setup-screen screen-enter"><p className="eyebrow">{joinCode ? 'BEITRITT ZUR LOBBY' : 'SPIEL ERSTELLEN'}</p><h2>WER BIST DU HEUTE?</h2><label className="field-label">DEIN NAME</label><input className="name-input" value={name} onChange={(e) => setName(e.target.value.slice(0, 16))} placeholder="Dein Name" /><p className="field-label">WÄHLE DEIN EMOJI</p><div className="avatar-picker">{avatars.map((item) => <button key={item} className={avatar === item ? 'avatar-choice active' : 'avatar-choice'} onClick={() => setAvatar(item)}>{item}</button>)}</div><button className="button button-primary full" disabled={!name.trim()} onClick={joinCode ? joinRoom : createRoom}>{joinCode ? 'LOBBY BETRETEN' : 'LOBBY ERSTELLEN'} <span>→</span></button></section>}
    {screen === 'lobby' && room && <Lobby room={room} isHost={isHost} player={player} updateSettings={updateSettings} send={send} start={start} />}
    {screen === 'questions' && room && <section className="draft-screen panel screen-enter"><p className="eyebrow">EIGENE FRAGEN</p><h2>WAS WOLLT IHR RANKEN?</h2><p>Alle geben bis zu drei Fragen ab. Fortschritt: {room.questionProgress} / {room.questionTarget}</p><div className="draft-list">{questions.map((value, index) => <label className="draft-field" key={index}><span>{index + 1}</span><input value={value} onChange={(e) => setQuestions(questions.map((q, i) => i === index ? e.target.value : q))} placeholder="Wer würde am ehesten ...?" /></label>)}</div><button className="button button-primary full" onClick={() => send({ type: 'questions_submitted', questions })}>FRAGEN ABGEBEN <Send size={17} /></button>{isHost && <button className="button button-secondary full" onClick={start}>WENN ALLE FERTIG SIND: STARTEN</button>}</section>}
    {screen === 'ranking' && room && <section className="rank-screen screen-enter"><div className="round-top"><span>RUNDE 1 / {room.settings.rounds} · FRAGE 1 / {room.settings.questionCount}</span><span className="timer-pill">GEHEIM</span></div><p className="eyebrow">RANKE DEINE FREUNDE</p><h2>{question}</h2><p className="rank-help">Halte den Griff und ziehe eine Karte zwischen zwei Plätze. Deine Reihenfolge bleibt geheim.</p><div className="ranking-list">{order.map((id, index) => { const entry = room.players.find((p) => p.id === id)!; return <article className={`rank-card ${dragged === id ? 'dragging' : ''}`} key={id} onPointerEnter={() => { if (dragged && dragged !== id) setOrder((current) => insert(current, current.indexOf(dragged), index)); }}><span className="place">{index + 1}</span><span className="rank-avatar">{entry.avatar}</span><strong>{entry.name}</strong><button className="drag-handle" onPointerDown={(e) => { e.currentTarget.setPointerCapture(e.pointerId); setDragged(id); }} onPointerUp={() => setDragged(null)} aria-label={`${entry.name} verschieben`}><GripVertical size={22} /></button></article>; })}</div><button className="button button-primary full" onClick={submitRanking}>RANKING ABGEBEN <Send size={17} /></button></section>}
    {screen === 'waiting' && <section className="waiting-screen panel screen-enter"><div className="done-mark">✓</div><p className="eyebrow">FERTIG</p><h2>DEIN RANKING IST SICHER.</h2><p>Warte, bis die übrigen Spieler:innen abgegeben haben.</p></section>}
    {screen === 'reveal' && <section className="reveal-screen screen-enter"><p className="eyebrow">DIE GRUPPE HAT ENTSCHIEDEN</p><h2>ALLE RANKINGS SIND DA.</h2><p className="reveal-note">Der Ergebnis-Reveal folgt als nächster Spielschritt.</p></section>}
  </main>;
}

function Lobby({ room, isHost, player, updateSettings, send, start }: { room: RoomState; isHost: boolean; player?: Player; updateSettings: (patch: Partial<Settings>) => void; send: (event: ClientEvent) => void; start: () => void }) {
  const settings = room.settings;
  return <section className="lobby-screen screen-enter"><div className="lobby-heading"><p className="eyebrow">PRIVATE LOBBY · {isHost ? 'DU BIST HOST' : 'DU BIST GAST'}</p><h2>{isHost ? 'DEINE CREW IST FAST KOMPLETT.' : 'DU BIST DABEI!'}</h2><p>{isHost ? 'Nur du stellst das Spiel ein und startest die Runde.' : 'Warte auf den Host. Du kannst dich bereit melden.'}</p></div><div className="lobby-grid"><article className="invite-card"><p>DEIN RAUMCODE</p><strong>{room.code}</strong><button className="copy-link" onClick={() => navigator.clipboard?.writeText(room.code)}><Share2 size={16} /> CODE KOPIEREN</button></article>{isHost ? <HostSettings settings={settings} update={updateSettings} /> : <article className="guest-card"><UsersRound size={28} /><strong>LOBBY-REGELN</strong><span>{settings.questionCount} Fragen · {settings.rounds} Runden</span><span>{settings.mode === 'friends' ? 'Rank The Friends' : 'Guess My Rank'} · {settings.questionSource === 'custom' ? 'eigene Fragen' : 'vorgegebene Fragen'}</span></article>}</div>{isHost && <ModeSettings settings={settings} update={updateSettings} />}<div className="player-grid">{room.players.map((entry) => <article className={entry.id === room.hostId ? 'player-card host' : 'player-card'} key={entry.id}><span>{entry.avatar}</span><strong>{entry.name}</strong>{entry.id === room.hostId && <small>HOST</small>}{entry.ready && <em>bereit</em>}</article>)}</div><div className="lobby-footer">{isHost ? <><span><i /> {room.players.filter((p) => p.ready).length} / {room.players.length} BEREIT</span><button className="button button-primary" disabled={room.players.length < 2 || !room.players.every((p) => p.ready)} onClick={start}>ALS HOST STARTEN <span>→</span></button></> : <button className="button button-primary full" onClick={() => send({ type: 'ready_updated', ready: !player?.ready })}>{player?.ready ? 'NICHT BEREIT' : 'ICH BIN BEREIT'} <span>→</span></button>}</div></section>;
}
function HostSettings({ settings, update }: { settings: Settings; update: (patch: Partial<Settings>) => void }) { return <article className="settings-card host-settings"><div className="setting-block"><span className="setting-title">WIE VIELE FRAGEN?</span><div className="choice-row">{[2, 3, 4].map((v) => <button key={v} className={settings.questionCount === v ? 'choice-button selected' : 'choice-button'} onClick={() => update({ questionCount: v as 2 | 3 | 4 })}>{v} Fragen</button>)}</div></div><div className="setting-block"><span className="setting-title">WIE VIELE RUNDEN?</span><div className="choice-row">{[1, 2, 3].map((v) => <button key={v} className={settings.rounds === v ? 'choice-button selected' : 'choice-button'} onClick={() => update({ rounds: v as 1 | 2 | 3 })}>{v} Runden</button>)}</div></div></article>; }
function ModeSettings({ settings, update }: { settings: Settings; update: (patch: Partial<Settings>) => void }) { return <><section className="mode-section"><p className="eyebrow">SPIELMODUS</p><div className="mode-grid"><button className={settings.mode === 'friends' ? 'mode-card active friends-mode' : 'mode-card'} onClick={() => update({ mode: 'friends' })}><strong>RANK THE FRIENDS</strong><span>Ihr rankt euch gegenseitig zu einer Frage.</span></button><button className={settings.mode === 'guess' ? 'mode-card active guess-mode' : 'mode-card'} onClick={() => update({ mode: 'guess' })}><strong>GUESS MY RANK</strong><span>Die Gruppe errät die richtige Reihenfolge.</span></button></div></section><section className="question-source"><p className="eyebrow">FRAGEQUELLE</p><div className="source-grid"><button className={settings.questionSource === 'preset' ? 'source-card active' : 'source-card'} onClick={() => update({ questionSource: 'preset' })}><strong>✨ VORGEGEBEN</strong><small>Sofort spielbereit.</small></button><button className={settings.questionSource === 'custom' ? 'source-card active' : 'source-card'} onClick={() => update({ questionSource: 'custom' })}><strong>✍️ EIGENE FRAGEN</strong><small>Alle geben 2–3 Fragen ab.</small></button></div></section></>; }
