import { createServer } from 'node:http';
import { randomBytes, randomUUID } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { WebSocketServer } from 'ws';

const PORT = Number(process.env.PORT || 8787), DATA_FILE = process.env.DATA_FILE || '/data/rooms.json';
const ROOM_TTL_MS = 1000 * 60 * 60 * 12, COUNTDOWN_MS = 3000;
const rooms = new Map(), connections = new Map(), countdownTimers = new Map(), botTimers = new Map(), guessTimers = new Map();
const defaultSettings = { questionCount: 3, customQuestionsPerPlayer: 1, mode: 'friends', questionSource: 'preset' };
const presetQuestions = ['Wer würde am ehesten einen Roadtrip spontan verlängern?', 'Wer bringt die Gruppe am schnellsten zum Lachen?', 'Wer würde in einer Zombie-Apokalypse am längsten durchhalten?', 'Wer ist am besten darin, Geheimnisse zu bewahren?', 'Wer würde am ehesten zu spät zur eigenen Party kommen?', 'Wer hat den besten Musikgeschmack?', 'Wer würde am ehesten eine neue Sprache lernen?', 'Wer ist der beste Teamplayer?', 'Wer würde am ehesten berühmt werden?', 'Wer macht die besten Mitternachtssnacks?'];
function load() { if (!existsSync(DATA_FILE)) return; for (const room of JSON.parse(readFileSync(DATA_FILE, 'utf8')).rooms || []) { room.settings = { ...defaultSettings, ...room.settings, customQuestionsPerPlayer: room.settings?.customQuestionsPerPlayer || 1 }; room.questions ||= []; room.roundResults ||= []; room.cumulativeScores ||= {}; room.guessQuestions ||= []; room.guessAuthorOrder ||= []; room.guessAnswers ||= {}; room.guessRoundScores ||= {}; room.guessCumulativeScores ||= {}; rooms.set(room.code, room); } }
function save() { mkdirSync(new URL('.', `file://${DATA_FILE}`).pathname, { recursive: true }); writeFileSync(DATA_FILE, JSON.stringify({ rooms: [...rooms.values()] })); }
function code() { let value; do value = randomBytes(4).toString('base64url').toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 5); while (rooms.has(value)); return value; }
function calculateResults(room) { const values = new Map(room.players.map((p) => [p.id, { playerId: p.id, points: 0, firstPlaceVotes: 0 }])); for (const ranking of Object.values(room.rankings)) ranking.forEach((id, index) => { const e = values.get(id); if (e) { e.points += room.players.length - index; if (index === 0) e.firstPlaceVotes += 1; } }); const min = room.players.length, max = room.players.length ** 2; return [...values.values()].map((e) => ({ ...e, totalPoints: e.points, percent: max === min ? 100 : Math.round(((e.points - min) / (max - min)) * 100) })).sort((a, b) => b.totalPoints - a.totalPoints || b.firstPlaceVotes - a.firstPlaceVotes || a.playerId.localeCompare(b.playerId)); }
function shuffle(values) { return [...values].sort(() => Math.random() - 0.5); }
function prepareQuestions(room) { room.questions = room.settings.questionSource === 'custom' ? shuffle(Object.values(room.customQuestions).flat()) : shuffle(presetQuestions).slice(0, room.settings.questionCount); }
function publicRoom(room, viewerId) { const humanCount = room.players.filter((p) => !p.isBot).length; const currentGuess = room.guessQuestions?.[room.guessQuestionIndex || 0]; const guessView = room.settings.mode === 'guessFriend' ? { guessRole: room.phase === 'clue_writing' && room.guessAuthorId === viewerId ? 'author' : 'detective', ...(room.phase === 'clue_writing' && room.guessAuthorId === viewerId ? { guessOptions: room.players.map((p) => p.id) } : {}), ...(room.phase === 'guessing' ? { guessQuestionText: currentGuess?.text, guessOptions: room.players.filter((p) => p.id !== room.guessAuthorId).map((p) => p.id), guessDeadline: room.guessDeadline } : {}), ...(room.phase === 'guess_reveal' || room.phase === 'finished' ? { guessReveal: currentGuess ? { authorId: currentGuess.authorId, targetId: currentGuess.targetId, text: currentGuess.text, scores: room.guessRoundScores || {} } : undefined } : {}) } : {}; return { code: room.code, hostId: room.hostId, phase: room.phase, players: room.players.map(({ token, ...p }) => p), settings: room.settings, questions: room.questions, totalQuestions: room.questions?.length || room.settings.questionCount, updatedAt: room.updatedAt, countdownEndsAt: room.countdownEndsAt, revealIndex: room.revealIndex, questionIndex: room.questionIndex || 0, questionProgress: Object.keys(room.customQuestions).length, questionTarget: humanCount, ...guessView, ...(room.phase === 'reveal' || room.phase === 'finished' ? { results: room.results } : {}) }; }
function touch(room) { room.updatedAt = Date.now(); save(); broadcast(room); }
function broadcast(room) { for (const p of room.players) { const ws = connections.get(p.id); if (ws?.readyState === 1) ws.send(JSON.stringify({ type: 'room_state', room: publicRoom(room, p.id) })); } }
function error(ws, message) { ws.send(JSON.stringify({ type: 'error', message })); }
function getRoom(roomCode) { const room = rooms.get(roomCode); if (!room) return null; if (Date.now() - room.updatedAt >= ROOM_TTL_MS) { rooms.delete(roomCode); clearTimeout(countdownTimers.get(roomCode)); clearTimeout(guessTimers.get(roomCode)); for (const timer of botTimers.get(roomCode) || []) clearTimeout(timer); countdownTimers.delete(roomCode); guessTimers.delete(roomCode); botTimers.delete(roomCode); save(); return null; } return room; }
function validSettings(settings) { return settings && Number.isInteger(settings.questionCount) && settings.questionCount >= 1 && settings.questionCount <= 10 && Number.isInteger(settings.customQuestionsPerPlayer) && settings.customQuestionsPerPlayer >= 1 && settings.customQuestionsPerPlayer <= 5 && ['friends', 'guess', 'guessFriend'].includes(settings.mode) && ['preset', 'custom'].includes(settings.questionSource); }
function body(req) { return new Promise((resolve, reject) => { let raw = ''; req.on('data', (chunk) => raw += chunk); req.on('end', () => { try { resolve(JSON.parse(raw || '{}')); } catch { reject(new Error('Ungültige Anfrage.')); } }); }); }
function validProfile({ name, avatar }) { return typeof name === 'string' && name.trim().length >= 1 && name.trim().length <= 16 && typeof avatar === 'string' && [...avatar].length <= 4; }
function player(name, avatar) { return { id: randomUUID(), token: randomUUID(), name: name.trim(), avatar, joinedAt: Date.now(), ready: false, connected: false }; }
function finishRankingIfReady(room) { if (Object.keys(room.rankings).length !== room.players.length) return false; const round = calculateResults(room); room.roundResults.push(round); for (const result of round) room.cumulativeScores[result.playerId] = (room.cumulativeScores[result.playerId] || 0) + result.points; room.results = round; room.revealIndex = 0; room.phase = 'reveal'; return true; }
function scheduleBotRankings(room) { for (const timer of botTimers.get(room.code) || []) clearTimeout(timer); const timers = room.players.filter((p) => p.isBot).map((bot, index) => setTimeout(() => { const current = rooms.get(room.code); if (!current || current.phase !== 'ranking') return; const order = current.players.map((p) => p.id).sort(() => Math.random() - 0.5); current.rankings[bot.id] = order; finishRankingIfReady(current); touch(current); }, 700 + index * 650)); botTimers.set(room.code, timers); }
function beginCountdown(room) { clearTimeout(countdownTimers.get(room.code)); room.phase = 'countdown'; room.countdownEndsAt = Date.now() + COUNTDOWN_MS; touch(room); countdownTimers.set(room.code, setTimeout(() => { const current = rooms.get(room.code); if (!current || current.phase !== 'countdown') return; current.phase = 'ranking'; delete current.countdownEndsAt; scheduleBotRankings(current); touch(current); countdownTimers.delete(room.code); }, COUNTDOWN_MS)); }
function beginGuessing(room) { const question = room.guessQuestions[room.guessQuestionIndex || 0]; room.phase = 'guessing'; room.guessStartedAt = Date.now(); room.guessDeadline = room.guessStartedAt + 20000; clearTimeout(guessTimers.get(room.code)); guessTimers.set(room.code, setTimeout(() => { const current = rooms.get(room.code); if (!current || current.phase !== 'guessing') return; completeGuessReveal(current); touch(current); }, 20000)); }
function completeGuessReveal(room) { const question = room.guessQuestions[room.guessQuestionIndex || 0]; if (!question) return; clearTimeout(guessTimers.get(room.code)); room.guessRoundScores = {}; for (const p of room.players.filter((entry) => !entry.isBot && entry.id !== question.authorId)) { const answer = room.guessAnswers[p.id]; const score = answer?.targetId === question.targetId ? Math.round(1000 - Math.min(1, Math.max(0, (answer.submittedAt - room.guessStartedAt) / 20000)) * 900) : 0; room.guessRoundScores[p.id] = score; room.guessCumulativeScores[p.id] = (room.guessCumulativeScores[p.id] || 0) + score; } room.phase = 'guess_reveal'; }
function finishGuessGame(room) { room.phase = 'finished'; room.results = room.players.filter((p) => !p.isBot).map((p) => ({ playerId: p.id, points: room.guessCumulativeScores[p.id] || 0, totalPoints: room.guessCumulativeScores[p.id] || 0, percent: 0, firstPlaceVotes: 0 })).sort((a, b) => b.totalPoints - a.totalPoints || a.playerId.localeCompare(b.playerId)); }

load();
const server = createServer(async (req, res) => { res.setHeader('Content-Type', 'application/json'); res.setHeader('Access-Control-Allow-Origin', process.env.CORS_ORIGIN || '*'); res.setHeader('Access-Control-Allow-Headers', 'Content-Type'); if (req.method === 'OPTIONS') return res.end(); try {
  if (req.method === 'GET' && /^\/api\/rooms\/[A-Z0-9]{5}$/.test(req.url)) { const room = getRoom(req.url.split('/').pop()); if (!room) { res.statusCode = 404; return res.end(JSON.stringify({ error: 'Lobby nicht gefunden oder abgelaufen.' })); } return res.end(JSON.stringify({ room: publicRoom(room) })); }
  if (req.method === 'POST' && req.url === '/api/rooms') { const profile = await body(req); if (!validProfile(profile)) throw new Error('Bitte Name und Emoji ausfüllen.'); const host = player(profile.name, profile.avatar); host.ready = true; const room = { code: code(), hostId: host.id, phase: 'lobby', players: [host], settings: { ...defaultSettings }, customQuestions: {}, questions: [], roundResults: [], cumulativeScores: {}, rankings: {}, results: [], questionIndex: 0, guessQuestions: [], guessQuestionIndex: 0, guessAuthorOrder: [], guessAuthorId: null, guessAnswers: {}, guessRoundScores: {}, guessCumulativeScores: {}, updatedAt: Date.now() }; rooms.set(room.code, room); save(); return res.end(JSON.stringify({ code: room.code, playerId: host.id, token: host.token, room: publicRoom(room) })); }
  const match = req.url.match(/^\/api\/rooms\/([A-Z0-9]{5})\/join$/); if (req.method === 'POST' && match) { const room = getRoom(match[1]), profile = await body(req); if (!room) { res.statusCode = 404; return res.end(JSON.stringify({ error: 'Lobby nicht gefunden oder abgelaufen.' })); } if (room.phase !== 'lobby') { res.statusCode = 409; return res.end(JSON.stringify({ error: 'Diese Runde hat bereits begonnen.' })); } if (room.players.length >= 10) { res.statusCode = 409; return res.end(JSON.stringify({ error: 'Diese Lobby ist voll.' })); } if (!validProfile(profile)) throw new Error('Bitte Name und Emoji ausfüllen.'); const guest = player(profile.name, profile.avatar); room.players.push(guest); touch(room); return res.end(JSON.stringify({ code: room.code, playerId: guest.id, token: guest.token, room: publicRoom(room) })); }
  const reconnect = req.url.match(/^\/api\/rooms\/([A-Z0-9]{5})\/reconnect$/); if (req.method === 'POST' && reconnect) { const room = getRoom(reconnect[1]), credentials = await body(req), restored = room?.players.find((p) => p.id === credentials.playerId && p.token === credentials.token); if (!room || !restored) { res.statusCode = 401; return res.end(JSON.stringify({ error: 'Deine Lobby-Session ist nicht mehr gültig.' })); } return res.end(JSON.stringify({ code: room.code, playerId: restored.id, token: restored.token, room: publicRoom(room) })); }
  res.statusCode = 404; res.end(JSON.stringify({ error: 'Nicht gefunden.' }));
} catch (err) { res.statusCode = 400; res.end(JSON.stringify({ error: err.message })); } });

const wss = new WebSocketServer({ noServer: true });
server.on('upgrade', (req, socket, head) => { const url = new URL(req.url, `http://${req.headers.host}`); if (url.pathname !== '/ws') return socket.destroy(); wss.handleUpgrade(req, socket, head, (ws) => { ws.context = { code: url.searchParams.get('code'), playerId: url.searchParams.get('playerId'), token: url.searchParams.get('token') }; wss.emit('connection', ws); }); });
wss.on('connection', (ws) => { const { code: roomCode, playerId, token } = ws.context, room = getRoom(roomCode), connectedPlayer = room?.players.find((p) => p.id === playerId && p.token === token); if (!room || !connectedPlayer) return ws.close(1008, 'Nicht autorisiert'); connectedPlayer.connected = true; connections.set(playerId, ws); touch(room);
  ws.on('message', (raw) => { try { const event = JSON.parse(raw), current = getRoom(roomCode), actor = current?.players.find((p) => p.id === playerId && p.token === token); if (!current || !actor) return error(ws, 'Lobby ist nicht mehr verfügbar.');
    if (event.type === 'settings_updated') { if (current.hostId !== actor.id || current.phase !== 'lobby') return error(ws, 'Nur der Host darf die Einstellungen ändern.'); if (!validSettings(event.settings)) return error(ws, 'Ungültige Spieleinstellungen.'); current.settings = event.settings; }
    else if (event.type === 'ready_updated') { if (current.phase !== 'lobby') return error(ws, 'Bereitschaft ist nur in der Lobby möglich.'); actor.ready = Boolean(event.ready); }
    else if (event.type === 'add_bot') { if (current.hostId !== actor.id || current.phase !== 'lobby') return error(ws, 'Nur der Host kann Test-Bots hinzufügen.'); if (current.players.length >= 10) return error(ws, 'Die Lobby ist voll.'); const bot = player(`Bot ${current.players.filter((p) => p.isBot).length + 1}`, ['🤖', '🦊', '🐸', '👽'][current.players.filter((p) => p.isBot).length % 4]); bot.isBot = true; bot.ready = true; bot.connected = true; current.players.push(bot); }
    else if (event.type === 'questions_submitted') { if (current.phase !== 'question_draft') return error(ws, 'Fragen können gerade nicht abgegeben werden.'); const submitted = Array.isArray(event.questions) ? event.questions.filter((q) => typeof q === 'string' && q.trim()).slice(0, current.settings.customQuestionsPerPlayer) : []; if (submitted.length !== current.settings.customQuestionsPerPlayer) return error(ws, `Bitte genau ${current.settings.customQuestionsPerPlayer} Frage${current.settings.customQuestionsPerPlayer === 1 ? '' : 'n'} abgeben.`); current.customQuestions[actor.id] = submitted; if (current.players.filter((p) => !p.isBot).every((p) => current.customQuestions[p.id]?.length === current.settings.customQuestionsPerPlayer)) { prepareQuestions(current); return beginCountdown(current); } }
    else if (event.type === 'cancel_countdown') { if (current.hostId !== actor.id || current.phase !== 'countdown') return error(ws, 'Nur der Host kann den Countdown abbrechen.'); clearTimeout(countdownTimers.get(current.code)); countdownTimers.delete(current.code); delete current.countdownEndsAt; current.phase = 'question_draft'; }
    else if (event.type === 'start_game') { if (current.hostId !== actor.id) return error(ws, 'Nur der Host kann starten.'); if (current.players.length < 2) return error(ws, 'Mindestens zwei Personen werden benötigt.'); if (!current.players.every((p) => p.ready)) return error(ws, 'Warte, bis alle bereit sind.'); if (current.settings.mode === 'guessFriend') { if (current.players.some((p) => p.isBot)) return error(ws, 'Guess The Friend läuft ohne Bots.'); current.guessAuthorOrder = shuffle(current.players.map((p) => p.id)); current.guessQuestionIndex = 0; current.guessQuestions = []; current.guessAnswers = {}; current.guessRoundScores = {}; current.guessCumulativeScores = {}; current.guessAuthorId = current.guessAuthorOrder[0]; current.phase = 'clue_writing'; } else if (current.settings.questionSource === 'custom' && current.phase === 'lobby') current.phase = 'question_draft'; else if (current.settings.questionSource === 'preset') { prepareQuestions(current); current.phase = 'ranking'; scheduleBotRankings(current); } else return error(ws, 'Warte auf die Fragen der Gruppe.'); }
    else if (event.type === 'guess_question_submitted') { if (current.settings.mode !== 'guessFriend' || current.phase !== 'clue_writing' || current.guessAuthorId !== actor.id) return error(ws, 'Du bist gerade nicht als Autor dran.'); const text = typeof event.text === 'string' ? event.text.trim() : ''; if (text.length < 3 || text.length > 160) return error(ws, 'Der Hinweis muss 3 bis 160 Zeichen lang sein.'); if (!current.players.some((p) => !p.isBot && p.id === event.targetId)) return error(ws, 'Diese Zielperson gibt es nicht.'); current.guessQuestions[current.guessQuestionIndex] = { authorId: actor.id, targetId: event.targetId, text }; current.guessAnswers = {}; beginGuessing(current); }
    else if (event.type === 'guess_answer_submitted') { if (current.settings.mode !== 'guessFriend' || current.phase !== 'guessing') return error(ws, 'Die Tipp-Runde ist nicht aktiv.'); const question = current.guessQuestions[current.guessQuestionIndex]; if (actor.id === question.authorId) return error(ws, 'Der Autor tippt in dieser Runde nicht mit.'); if (current.guessAnswers[actor.id]) return error(ws, 'Dein Tipp wurde bereits abgegeben.'); if (!current.players.some((p) => !p.isBot && p.id === event.targetId)) return error(ws, 'Diese Antwort ist ungültig.'); current.guessAnswers[actor.id] = { targetId: event.targetId, submittedAt: Date.now() }; }
    else if (event.type === 'guess_reveal') { if (current.settings.mode !== 'guessFriend' || current.hostId !== actor.id || current.phase !== 'guessing') return error(ws, 'Der Host kann erst nach allen Tipps oder dem Timer auflösen.'); const question = current.guessQuestions[current.guessQuestionIndex]; const expected = current.players.filter((p) => !p.isBot && p.id !== question.authorId).length; if (Object.keys(current.guessAnswers).length < expected && Date.now() < current.guessDeadline) return error(ws, 'Warte noch auf die übrigen Tipps.'); completeGuessReveal(current); }
    else if (event.type === 'ranking_submitted') { if (current.phase !== 'ranking') return error(ws, 'Ranking ist noch nicht aktiv.'); const valid = Array.isArray(event.order) && event.order.length === current.players.length && new Set(event.order).size === current.players.length && event.order.every((id) => current.players.some((p) => p.id === id)); if (!valid) return error(ws, 'Dieses Ranking ist ungültig.'); current.rankings[actor.id] = event.order; actor.ready = true; finishRankingIfReady(current); }
    else if (event.type === 'reveal_next') { if (current.hostId !== actor.id || current.phase !== 'reveal') return error(ws, 'Nur der Host kann den Reveal fortsetzen.'); current.revealIndex = Math.min(current.players.length, (current.revealIndex || 0) + 1); }
    else if (event.type === 'next_question') { if (current.settings.mode === 'guessFriend') { if (current.hostId !== actor.id || current.phase !== 'guess_reveal') return error(ws, 'Nur der Host kann die nächste Frage starten.'); if ((current.guessQuestionIndex || 0) + 1 >= current.guessAuthorOrder.length) finishGuessGame(current); else { current.guessQuestionIndex += 1; current.guessAuthorId = current.guessAuthorOrder[current.guessQuestionIndex]; current.guessAnswers = {}; current.guessRoundScores = {}; delete current.guessDeadline; current.phase = 'clue_writing'; } } else { if (current.hostId !== actor.id || current.phase !== 'reveal') return error(ws, 'Nur der Host kann die nächste Frage starten.'); if ((current.revealIndex || 0) < current.players.length) return error(ws, 'Der Reveal ist noch nicht fertig.'); if ((current.questionIndex || 0) + 1 >= current.questions.length) { current.phase = 'finished'; current.results = current.players.map((p) => ({ playerId: p.id, points: current.cumulativeScores[p.id] || 0, totalPoints: current.cumulativeScores[p.id] || 0, percent: 0, firstPlaceVotes: 0 })).sort((a, b) => b.totalPoints - a.totalPoints || a.playerId.localeCompare(b.playerId)); } else { current.questionIndex = (current.questionIndex || 0) + 1; current.rankings = {}; current.results = []; current.revealIndex = 0; current.players.forEach((p) => { p.ready = Boolean(p.isBot); }); current.phase = 'ranking'; scheduleBotRankings(current); } } }
    else return error(ws, 'Unbekannte Aktion.'); touch(current);
  } catch { error(ws, 'Ungültige Nachricht.'); } });
  ws.on('close', () => { const current = getRoom(roomCode); if (!current) return; const entry = current.players.find((p) => p.id === playerId); if (entry) entry.connected = false; if (connections.get(playerId) === ws) connections.delete(playerId); if (current.hostId === playerId) current.hostId = current.players.filter((p) => p.id !== playerId).sort((a, b) => a.joinedAt - b.joinedAt)[0]?.id || playerId; touch(current); }); });
setInterval(() => { for (const [key, room] of rooms) if (Date.now() - room.updatedAt > ROOM_TTL_MS) rooms.delete(key); save(); }, 60_000);
server.listen(PORT, () => console.log(`Friends Rank server on :${PORT}`));
