export type Player = { id: string; name: string; avatar: string; score: number };
export type FriendQuestion = { id: string; text: string; category: 'FUNNY' | 'FRIENDSHIP' | 'PERSONALITY' | 'PARTY' };
export const friendQuestions: FriendQuestion[] = ['im Gefaengnis landen','eine Zombie-Apokalypse ueberleben','aus Versehen beruehmt werden','seinen Flug verpassen','bei einer Realityshow mitmachen','Buergermeister werden','eine Woche ohne Handy schaffen','einen Roadtrip spontan starten','eine Hochzeit vergessen','nachts um 3 Uhr wach sein','Millionaer werden','einen Gruppenchat leaken','ein Geheimnis aus Versehen verraten','zu spaet zur eigenen Hochzeit kommen','bei einem Quiz gewinnen','eine Rede ohne Vorbereitung halten','eine Pflanze am Leben halten','eine verrueckte Geschaeftsidee starten','am laengsten tanzen','den besten Snack mitbringen','einen fremden Hund mitnehmen','eine Karaoke-Buehne erobern','sich im Urlaub verlaufen','eine Party als Letzte:r verlassen','am besten improvisieren','einen peinlichen Trend feiern','in einer Gameshow gewinnen','eine Ueberraschung ruinieren','einen Lachanfall bekommen','einen Podcast starten','am ehesten umziehen','einen Schatz finden','eine Band gruenden','einen schlechten Witz lieben','ein Jahr ohne Kaffee schaffen','ein Meeting retten','am meisten ueberdenken','am zuverlaessigsten sein','am spontansten sein','am geheimnisvollsten sein','die beste Playlist haben','den besten Rat geben','eine neue Sprache lernen','einen Kochkurs gewinnen','am besten Geschichten erzaehlen','eine Freundschaft verkuppeln','beim Camping dominieren','den perfekten Geburtstag planen','am meisten Fotos machen','einen Tanztrend erfinden'].map((text, index) => ({ id: `friend-${index + 1}`, text: `WER WUERDE AM EHESTEN ${text.toUpperCase()}?`, category: ['FUNNY','FRIENDSHIP','PERSONALITY','PARTY'][index % 4] as FriendQuestion['category'] }));
export const rankingCategories = [['Lieblingsfruechte',['Mango','Erdbeere','Wassermelone','Kirsche','Banane']],['Fast-Food-Ketten',['Burger','Pizza','Doener','Sushi','Tacos']],['Serien',['Comedy','Drama','Anime','Krimi','Reality']],['Filme',['Action','Comedy','Horror','Sci-Fi','Animation']],['Videospiele',['Racing','Sport','Puzzle','RPG','Shooter']],['Urlaubslaender',['Italien','Japan','Spanien','Island','Portugal']],['Getraenke',['Eistee','Kaffee','Limo','Smoothie','Wasser']],['Apps',['Musik','Chat','Maps','Video','Notizen']],['Schulfaecher',['Kunst','Sport','Bio','Geschichte','Mathe']],['Traumautos',['Oldtimer','Elektro','Sportwagen','Van','Cabrio']],['Staedte',['Berlin','Lissabon','Seoul','Paris','New York']],['Musikgenres',['Pop','Rap','Rock','Techno','Indie']],['Dinge fuer eine Insel',['Musik','Freunde','Snacks','Buecher','Sonne']],['Lieblingssnacks',['Chips','Schokolade','Popcorn','Obst','Nuesse']],['Wochenendplaene',['Party','Gaming','Sport','Ausflug','Sofa']],['Superkraefte',['Fliegen','Zeitreise','Unsichtbar','Teleportieren','Gedanken lesen']],['Traumjobs',['Creator','Koch','Pilot','Designer','Tierarzt']],['Haustiere',['Hund','Katze','Kaninchen','Fisch','Gecko']],['Eissorten',['Vanille','Schoko','Zitrone','Erdbeere','Pistazie']],['Fruehstueck',['Pfannkuchen','Muesli','Brot','Obst','Nichts']]].map(([title, items], index) => ({ id: `category-${index + 1}`, title: `DEINE TOP 5: ${title}`, items }));
export type BordaResult = { player: Player; points: number; percent: number; firstPlaceVotes: number };
export function calculateBordaResults(players: Player[], rankings: string[][], selfRanking: boolean): BordaResult[] {
  const values = new Map(players.map((player) => [player.id, { player, points: 0, firstPlaceVotes: 0 }]));
  rankings.forEach((ranking, voterIndex) => ranking.forEach((id, position) => { const entry = values.get(id); if (!entry || (!selfRanking && players[voterIndex]?.id === id)) return; entry.points += ranking.length - position; if (position === 0) entry.firstPlaceVotes += 1; }));
  const voterCount = selfRanking ? players.length : Math.max(1, players.length - 1); const ranksPerVote = selfRanking ? players.length : Math.max(1, players.length - 1); const min = voterCount; const max = voterCount * ranksPerVote;
  return [...values.values()].map((entry) => ({ ...entry, percent: max === min ? 100 : Math.round(((entry.points - min) / (max - min)) * 100) })).sort((a, b) => b.points - a.points || b.firstPlaceVotes - a.firstPlaceVotes || a.player.id.localeCompare(b.player.id));
}
